---
  - name: web server playbook. 
    hosts: web_setup
    tasks:
      - name: install httpd 
        yum:
          name: httpd
          state: present

      - name: copy some content in index file.
        file:
          path: /var/www/html/index.html

      - name: start and enable httpd 
        service:
          name: http
          state: started
          enabled: yes

